Repository wjdgml3834/mandarin_market, pull requests merged in 2022-03, with the labels that each got.

#37 Search/user
  src/components/research/Card.tsx
  src/components/research/Header.tsx
  src/components/research/Main.tsx
  src/pages/research.tsx
Labels: 기능

#38 ✨상황에 맞게 좋아요 post, delete 요청 및 실시간 적용
  src/components/home/Card.tsx
  src/components/home/CardContainer.tsx
Labels: 기능

#39 User/profile
  src/components/ProfileForm.tsx
  src/components/myProfile/Info.tsx
  src/components/myProfile/LogOutModal.tsx
  src/pages/myprofile/edit.tsx
  src/pages/myprofile/index.tsx
Labels: 기능

#40 ✨ 상품 등록, 수정, 모달 구현
  src/components/myProfile/MyContainer.tsx
  src/components/product/EditContainer.tsx
  src/components/product/FileUpload.tsx
  src/components/product/Modification.tsx
  src/components/product/ProductDeleteModal.tsx
  src/components/product/ProductModal.tsx
  src/components/product/Register.tsx
  src/components/yourProfile/Carousel.tsx
  src/components/yourProfile/CarouselCard.tsx
  src/pages/product/[...params].tsx
  src/pages/product/index.tsx
  src/types/Product.ts
Labels: 논의, 기능

#41 ♻️ Home/feed/refactoring
  src/components/home/Card.tsx
Labels: 기능, UI

#42 🐛 홈 화면 캐러셀 버그 수정
  src/components/home/Card.tsx
  src/components/home/Main.tsx
Labels: 기능, UI

#43 🐛 홈 화면 캐러셀 추가 버그 수정
  src/components/home/Card.tsx
Labels: 기능

#44 ✨ 홈피드 유저 게시물 신고 모달 구현
  src/components/home/Card.tsx
  src/components/home/Footer.tsx
  src/components/home/ReportCancelModal.tsx
  src/components/home/ReportModal.tsx
  src/pages/myprofile/[...params].tsx
Labels: 논의, 기능, UI

#48 ♻️ 프로필, 회원가입 폴더 구조 변경 및 리팩토링
  src/components/follower/Footer.tsx
  src/components/home/Card.tsx
  src/components/home/Footer.tsx
  src/components/home/Nonfeed.tsx
  src/components/home/ReportModal.tsx
  src/components/login/Email.tsx
  src/components/postDetail/CommentList.tsx
  src/components/postDetail/Container.tsx
  src/components/postUpload/PostEdit.tsx
  src/components/postUpload/PostUpload.tsx
  src/components/product/FileUpload.tsx
  src/components/product/Modification.tsx
  src/components/product/ProductDeleteModal.tsx
  src/components/product/Register.tsx
  src/components/profile/Carousel.tsx
  src/components/profile/CarouselCard.tsx
  src/components/profile/DeleteModal.tsx
  src/components/profile/Footer.tsx
  src/components/profile/Info.tsx
  src/components/profile/LogOutModal.tsx
  src/components/profile/MyContainer.tsx
  src/components/profile/MyPostCard.tsx
  src/components/profile/MyPostContainer.tsx
  src/components/profile/MyProfileModal.tsx
  src/components/profile/PostModal.tsx
  src/components/profile/ProfileAppPost.tsx
  src/components/profile/ProfilePost.tsx
  src/components/research/Card.tsx
  src/components/research/Footer.tsx
  src/components/research/Header.tsx
  src/components/research/Main.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/SignUpProfile.tsx
  src/components/we/Footer.tsx
  src/pages/post/[...params].tsx
  src/pages/profile/[...params].tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/signup.tsx
  src/types/MyPost.ts
Labels: 기능, UI

#49 ✨개발자 페이지 생성
  src/components/developer/Developer.tsx
  src/components/developer/Footer.tsx
  src/components/home/Footer.tsx
  src/components/profile/Footer.tsx
  src/components/research/Footer.tsx
  src/pages/chats/index.tsx
  src/pages/developer/index.tsx
Labels: UI

#50 Feature/followers refactoring
  src/components/follower/Card.tsx
  src/components/follower/CardContainer.tsx
  src/components/profile/Info.tsx
  src/pages/follow/[id]/follower.tsx
  src/types/Follower.ts
Labels: 논의, 기능

#52 ✨ Followings/feature
  src/components/following/Card.tsx
  src/components/following/CardContainer.tsx
  src/components/following/Footer.tsx
  src/components/following/Header.tsx
  src/components/following/Main.tsx
  src/components/profile/Info.tsx
  src/pages/follow/[id]/following.tsx
  src/types/Following.ts
Labels: 논의, 기능

#53 ✨ 개발자 페이지 소개 글 작성
  src/components/developer/Developer.tsx
Labels: UI

#54 ✨ StatusBar 현재 시간 구현
  src/components/layouts/StatusBar.tsx
Labels: 기능
