Repository wjdgml3834/mandarin_market, pull requests merged in 2022-01, with the labels that each got.

#3 Myprofile/header
  src/components/myProfile/Header.tsx
  src/components/myProfile/Info.tsx
  src/components/myProfile/LogOutModal.tsx
  src/components/myProfile/MyProfileModal.tsx
  src/pages/myprofile.tsx
  src/styles/reset.css
Labels: 기능, UI

#4 statusBar UI
  src/components/layouts/Layout.tsx
  src/components/layouts/StatusBar.tsx
  src/components/layouts/index.tsx
  src/pages/_app.tsx
Labels: UI

#5 SignUpPage/email
  src/components/signUp.tsx
  src/pages/signup.tsx
Labels: 기능, UI

#7 Login page/UI
  src/components/login/Email.tsx
  src/components/login/Main.tsx
  src/pages/index.tsx
  src/pages/login.tsx
Labels: 기능, UI

#8 Yourprofile/carousel
  src/components/Border.tsx
  src/components/myProfile/Header.tsx
  src/components/myProfile/LogOutModal.tsx
  src/components/myProfile/MyProfileModal.tsx
  src/components/yourProfile/Carousel.tsx
Labels: 기능, UI

#10 LoginPage/UI 이미지 추가
  public/images/ellipse-profile.svg
  public/images/facebook.svg
  public/images/google.svg
  public/images/kakao.svg
  src/components/login/Main.tsx
Labels: UI

#9 SignupPage/profile
  public/images/symbol-logo.svg
  public/images/upload-file.svg
  src/components/SignUpProfile.tsx
  src/components/signUp.tsx
  src/pages/signup.tsx
Labels: 기능, UI

#11 ✨ 프로필 수정 페이지 구현
  src/components/ProfileForm.tsx
  src/components/ProfileUpdate.tsx
  src/components/SignUpProfile.tsx
  src/components/myProfile/MyContainer.tsx
  src/pages/myprofile.tsx
Labels: 기능, UI

#12 채팅 목록 생성
  src/components/chats/ChatList.tsx
  src/components/layouts/StatusBar.tsx
  src/components/myProfile/MyContainer.tsx
  src/pages/chats/index.tsx
Labels: 기능, UI

#13 상품 등록 페이지 UI/유효성검사
  src/components/product/Container.tsx
  src/components/product/FileUpload.tsx
  src/components/product/Modification.tsx
  src/components/product/Register.tsx
  src/pages/product.tsx
Labels: 기능, UI

#14 ✨로그인 api 초기 설정
  src/components/chats/ChatList.tsx
  src/components/login/Email.tsx
  src/constants/index.ts
  src/hooks/useMandarinData.ts
  src/pages/chats/index.tsx
Labels: 기능

#15 게시글 작성 페이지 UI/기능 구현
  src/components/postUpload/Container.tsx
  src/components/postUpload/FileUpload.tsx
  src/components/postUpload/PostUpload.tsx
  src/pages/post/upload.tsx
Labels: 기능, UI

#16 Home/UI
  package.json
  src/components/home/Card.tsx
  src/components/home/CardContainer.tsx
  src/components/home/Footer.tsx
  src/components/home/Header.tsx
  src/components/home/Main.tsx
  src/components/home/Nonfeed.tsx
  src/img/symbol-logo.png
  src/pages/home.tsx
  src/pages/home/index.tsx
  src/types/Post.ts
  yarn.lock
Labels: 기능, UI

#17 ✨ Research 화면 UI 구현
  src/components/research/Card.tsx
  src/components/research/Footer.tsx
  src/components/research/Header.tsx
  src/components/research/Main.tsx
  src/pages/research.tsx
  src/types/Mandarin.ts
Labels: 기능, UI

#18 ✨ Followers/UI 페이지 구현
  src/components/follower/Card.tsx
  src/components/follower/CardContainer.tsx
  src/components/follower/Footer.tsx
  src/components/follower/Header.tsx
  src/components/follower/Main.tsx
  src/components/myProfile/Info.tsx
  src/pages/follower.tsx
  src/types/Follower.ts
Labels: 기능, UI

#20 게시글 상세 페이지 UI/기능 구현
  src/components/home/Card.tsx
  src/components/postDetail/Comment.tsx
  src/components/postDetail/CommentDelModal.tsx
  src/components/postDetail/CommentList.tsx
  src/components/postDetail/CommentModal.tsx
  src/components/postDetail/Container.tsx
  src/components/postDetail/DetailCard.tsx
  src/pages/postdetail/[id].tsx
Labels: 기능, UI
