Repository wjdgml3834/mandarin_market, pull requests merged in 2022-02, with the labels that each got.

#21 Myprofile/profilepost
  src/components/myProfile/MyContainer.tsx
  src/components/myProfile/ProfileAppPost.tsx
  src/components/myProfile/ProfilePost.tsx
Labels: 기능, UI

#22 🔧 엄격한 null 체크 false
  tsconfig.json
Labels: 제안

#24 ♻️ axios로 로그인 데이터 받아보기
  package-lock.json
  package.json
  src/components/login/Email.tsx
  src/components/myProfile/LogOutModal.tsx
  src/hooks/useMandarinData.ts
  tsconfig.json
  yarn.lock
Labels: 논의

#25 ➕ nextauth 로그인 기능
  package-lock.json
  package.json
  src/components/login/Email.tsx
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/hello.ts
  src/pages/index.tsx
  yarn.lock
Labels: 제안, 기능

#28 Custom 404 page/UI
  src/components/Custom404.tsx
  src/img/icon-404.png
  src/pages/404.tsx
Labels: 기능, UI

#29 backButton/feature
  src/components/BackButton.tsx
  src/components/ProfileForm.tsx
  src/components/ProfileUpdate.tsx
  src/components/chats/ChatList.tsx
  src/components/follower/Header.tsx
  src/components/home/Header.tsx
  src/components/home/Main.tsx
  src/components/login/Main.tsx
  src/components/myProfile/MyContainer.tsx
  src/components/myProfile/MyProfileModal.tsx
  src/components/postDetail/Container.tsx
  src/components/postUpload/Container.tsx
  src/components/postUpload/PostUpload.tsx
  src/components/product/Container.tsx
  src/components/product/Register.tsx
  src/components/research/Header.tsx
Labels: 논의, 기능, UI

#30 Signup/api
  src/components/ProfileForm.tsx
  src/components/SignUpProfile.tsx
  src/components/login/Email.tsx
  src/components/signUp.tsx
  src/img/profile.png
  src/pages/api/auth/[...nextauth].ts
  src/pages/signup.tsx
Labels: 기능

#31 ♻️ 회원가입 문제 해결 및 성공 실패 처리
  src/components/ProfileForm.tsx
  src/components/SignUpProfile.tsx
  src/components/signUp.tsx
Labels: 기능

#33 Myprofile/api
  src/components/myProfile/Info.tsx
  src/components/myProfile/MyPostCard.tsx
  src/components/myProfile/MyPostContainer.tsx
  src/components/myProfile/ProfilePost.tsx
  src/pages/api/auth/[...nextauth].ts
  src/types/MyPost.ts
Labels: 기능

#36 ♻️ 게시글 업로드 422 에러 해결
  src/components/postUpload/FileUpload.tsx
  src/components/postUpload/PostEdit.tsx
  src/components/postUpload/PostUpload.tsx
  src/pages/post/[...params].tsx
Labels: 기능
